import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <header className="bg-white shadow-md">
                <nav className="max-w-6xl mx-auto flex gap-6 p-4 items-center text-gray-800"> 
                <div className="font-bold text-xl text-orange-500 mr-4 font-mono">🍲 SmartRecipe</div>
                  <Link href="/" className="hover:text-orange-500 font-medium">Główna</Link>
                  <Link href="/about" className="hover:text-orange-500 font-medium">O nas</Link>
                  <Link href="/contact" className="hover:text-orange-500 font-medium">Kontakt</Link>
                </nav>
      </header>
        {children}
      </body>
    </html>
  );
}
