import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <header className="bg-white shadow-md">
        <nav className="flex gap-4 p-4 bg-gray-100">
          <Link href="/" className="hover:text-orange-500">Główna</Link>
          <Link href="/about" className="hover:text-orange-500">O nas</Link>
          <Link href="/contact" className="hover:text-orange-500">Kontakt</Link>
</nav>
      </header>
        {children}
      </body>
    </html>
  );
}
